name: Pylint Check

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install Dependencies and Run Pylint
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pylint-django
        pylint --load-plugins pylint_django --rcfile=.pylintrc **/**.py
